micronaut:
  application:
    name: book
datasources:
  default:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
jpa:
  default:
    packages-to-scan:
      - 'book.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
